package com.geekbrains;

public enum CommandType {
    FILE_MESSAGE,
    FILE_REQUEST,
    LIST_REQUEST,
    LIST_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTRATION_REQUEST,
    FILE_RESPONSE,
    FIRST_REQUEST,
    DELETE_REQUEST,
    DELETE_RESPONSE


}
